project:
  type: website

website:
  title: "Tyler Hillery"
  site-url: https://www.tylerhillery.com
  favicon: assets/images/favicon.ico
  image: assets/images/profile2.jpg
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://twitter.com
      - icon: mastodon
        href: https://twitter.com
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: custom.scss
    css: styles.css