project:
  type: website

website:
  title: "Tyler Hillery"
  site-url: https://www.tylerhillery.com
  favicon: assets/images/favicon.ico
  image: assets/images/profile2.jpg
  repo-url: https://github.com/TylerHillery/TylerHillery.github.io
  repo-actions: [edit, issue]
  comments:
    giscus:
      repo: quarto-dev/quarto-web
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
      - href: now.qmd
        text: Now
    right:
      - icon: github
        href: https://github.com/TylerHillery
      - icon: linkedin
        href: https://www.linkedin.com/in/tylerhillery/
      - icon: mastodon
        href: https://twitter.com/_TylerHillery
      - icon: twitter
        href: https://data-folks.masto.host/@TylerHillery
format:
  html:
    theme: custom.scss
    toc: true
    toc-location: left
    smooth-scroll: true
    code-line-numbers: true
execute:
  freeze: auto